In [1]:
import numpy as np

# Step 1: Initialize 3D array

data = np.arange(3*16*10).reshape(3,16,10)
print("Original Data Shape:",data.shape)
print(data)


Original Data Shape: (3, 16, 10)
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 21

In [2]:
# Step 2: Year-wise average

year_avg = data.mean(axis=(1,2))
print("\nYear-wise Average:")
print(year_avg)


Year-wise Average:
[ 79.5 239.5 399.5]


In [3]:
# Step 3: Student-wise total

student_total=data.sum(axis=(0,2))
print("\nStudent-wise Total:")
print(student_total)



Student-wise Total:
[4935 5235 5535 5835 6135 6435 6735 7035 7335 7635 7935 8235 8535 8835
 9135 9435]


In [4]:
# Step 4: Subject-wise highest score

subject_max=data.max(axis=(0,1))
print("\nSubject-wise Highest Score:")
print(subject_max)



Subject-wise Highest Score:
[470 471 472 473 474 475 476 477 478 479]


In [5]:
# Step 5: Replace marks below 40 with 40

data[data<40]=40
print("\nUpdated Data (Marks < 40 replaced with 40):")
print(data)



Updated Data (Marks < 40 replaced with 40):
[[[ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 21

In [7]:
# Step 6: Sort marks subject-wise

sorted_data = np.sort(data,axis=1)
print("\nSorted Data(Subject-wise):")
print(sorted_data)


Sorted Data(Subject-wise):
[[[ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  